application: temperatures-1214
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/images
  static_dir: static/images
- url: /static/bootstrap/css
  static_dir: static/bootstrap/css
- url: /stat
  script: pageStatistique.app
- url: /.*
  script: pagePrincipale.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest